// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['firebase_webKey'],
    appId: '1:340006461251:web:97a90c5fe935c960e599f6',
    messagingSenderId: '340006461251',
    projectId: 'travelmaker-66f58',
    authDomain: 'travelmaker-66f58.firebaseapp.com',
    storageBucket: 'travelmaker-66f58.appspot.com',
    measurementId: 'G-6S42VW2FW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['firebase_androidKey'],
    appId: '1:340006461251:android:da2fc602dff10bf5e599f6',
    messagingSenderId: '340006461251',
    projectId: 'travelmaker-66f58',
    storageBucket: 'travelmaker-66f58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['firebase_ios_macosKey'],
    appId: '1:340006461251:ios:f6fd2d2f9c8674b9e599f6',
    messagingSenderId: '340006461251',
    projectId: 'travelmaker-66f58',
    storageBucket: 'travelmaker-66f58.appspot.com',
    iosClientId: '340006461251-pubq3c5kiphtl08bvmsutjqtqa8daf06.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelmaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['firebase_ios_macosKey'],
    appId: '1:340006461251:ios:f6fd2d2f9c8674b9e599f6',
    messagingSenderId: '340006461251',
    projectId: 'travelmaker-66f58',
    storageBucket: 'travelmaker-66f58.appspot.com',
    iosClientId: '340006461251-pubq3c5kiphtl08bvmsutjqtqa8daf06.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelmaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['firebase_windowKey'],
    appId: '1:340006461251:web:cdd4ffa25c34481fe599f6',
    messagingSenderId: '340006461251',
    projectId: 'travelmaker-66f58',
    authDomain: 'travelmaker-66f58.firebaseapp.com',
    storageBucket: 'travelmaker-66f58.appspot.com',
    measurementId: 'G-50X136DT36',
  );
}
